### ISSUE TITLE
Add timestamp info in client log.

### ISSUE THREAD

**Issue by paul-guo-** [greenplum-db/plcontainer#125]
This applies to both r and python.

**Comment by HaozhouWang** [comment]
Fixed in https://github.com/greenplum-db/plcontainer/commit/8d4dd5a8abc8ec1b79e53e5ebd8bfa2aeaf59bcf

**Comment by HaozhouWang** [comment]
pin PR here: https://github.com/greenplum-db/plcontainer/pull/172
