### ISSUE TITLE
parse_container() should be refactored.

### ISSUE THREAD

**Issue by paul-guo-** [greenplum-db/plcontainer#227]
At least

1) Do xmlFree() before elog(ERROR, ...) to avoid mem leak.
2) Address similar concerns as https://github.com/greenplum-db/plcontainer/issues/226

**Comment by zhangh43** [comment]
https://github.com/greenplum-db/plcontainer/commit/b16e2184a5c4b65766c1fde0716dfa98961dd2a2

closed
