### ISSUE TITLE
Make plcontainer PostgreSQL compatible

### ISSUE THREAD

**Issue by paul-guo-** [greenplum-db/plcontainer#295]
Dave Cramer has an inital patch
https://github.com/greenplum-db/plcontainer/pull/2/files/7c5b15bc188accc7b719f1dd8eeb3ed107621fb7
Since the code changes a lot since then, more work need to be done. I'm creating the issue here so that later the support could be added later, hopefully not long.

**Comment by markwort** [comment]
I'm interested in making this postgres-compatible as well!
I've already made some baby steps in that direction, I'd like to know how you're doing :)
Could you add me to the project on Pivotal Tracker, maybe?

**Comment by davecramer** [comment]
@markwort it should not be difficult to make it pg compatible.

**Comment by markwort** [comment]
@davecramer indeed; I've got it running with fairly few changes. Right now, im stuck on several SELinux  alerts complaining about access to the unix socket that is used to exchange data between the executor and the container (If I understand the code correctly...).
I'm aware that gpdb isn't supposed to run on SELinux-enabled hosts, but that's not the case with postgres...

**Comment by davecramer** [comment]
@markwort my understanding is that you would need to add an SELinux policy to deal with that. 
This should be orthogonal to pl/container code.

**Comment by zhangh43** [comment]
@markwort , You can also refer to Dave's patch on make PLContainer PG compatible.
Follow the link [Dave's branch](https://github.com/paul-guo-/plcontainer-backup/commits/dc-postgres ) The first three commits are related to PG compatible.

Note That Dave's branch is not based on the current PLContainer master branch. And we introduce some Greenplum specific features in PLContainer later, For example, we use Greenplum resource group to manage the resource at the runtime level. Of course, you need to use macro to hide these codes.

**Comment by zhangh43** [comment]
@markwort  @davecramer 
I bring the Dave's branch on PG compatibility into the main repo.
Link: https://github.com/greenplum-db/plcontainer/tree/postgres-compatible-dave

**Comment by krait007** [comment]
hi @markwort @zhangh43 
I'm also interested in making this postgres-compatible！In the past two weeks，I tried to implement the initial version.  I submit a pr #361 just a moment ago.   Maybe we can implement this feature 
together.

**Comment by zhangh43** [comment]
@krait007  That's great!

**Comment by zhangh43** [comment]
@krait007 @markwort @davecramer 
Support PLContainer on Postgresql platform with solid quality is not simple task.
So I create project ProjectforPGCompatible(https://github.com/greenplum-db/plcontainer/projects/1) as the umbrella of all the issues related to Postgresql version
Feel free to add more issues into this project and welcome to pick up some issues to work on.

**Comment by krait007** [comment]
@zhangh43 
that's great!

**Comment by zhangh43** [comment]
Mark this issue as resolved, refer to merged PR https://github.com/greenplum-db/plcontainer/pull/361 for details. Note that this is the initial version of PLContainer on PG. More related issues please refer to https://github.com/greenplum-db/plcontainer/projects/1
