### ISSUE TITLE
Coredump is caused by elog in cleanup process

### ISSUE THREAD

**Issue by zhangh43** [greenplum-db/plcontainer#359]
We should not use elog in cleanup process under resource group mode.
Since resource group has the assumption that forked subprocess should not 
share/use the resource group slot at the same time

**Comment by paul-guo-** [comment]
Maybe we should create an issue now about using bg worker (pg 9.3 functionality) to do cleanup as some of us discussed? PG 9.3 functionatlies should be in gpdb master in a couple of months.
