### ISSUE TITLE
Open compile CFLAG "-Werror -Wall" for Postgresql Version

### ISSUE THREAD

**Issue by zhangh43** [greenplum-db/plcontainer#367]
Currently the compiling of PLContainer of postgresql version uses CFLAG: -Wextra -Wno-unused-but-set-variable.
We need to add "-Werror -Wall" as well to remove all the warnings just as PLContainer of greenplum version

Details refer to [PR361](https://github.com/greenplum-db/plcontainer/pull/361)

**Comment by krait007** [comment]
hi @zhangh43 
pg default have -Wdeclaration-after-statement  after `include $(PGXS)` ,   so there are some warnings:  "error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]" .
delete '-Wdeclaration-after-statement' or change the codes  which one is better?
