### ISSUE TITLE
GPDB in docker + PL/Container

### ISSUE THREAD

**Issue by yvaa** [greenplum-db/plcontainer#607]
Hello!

I'm trying to use PL/Container when GPDB is in docker and has an access to host docker daemon.

In short it looks like here:
![image](https://user-images.githubusercontent.com/58484982/81451149-86214e00-918c-11ea-9d4d-804dd6260333.png)

For now this is not working:

0. GPDB has access to host docker daemon
1. I run `SELECT function();`
2. `plc_coordinator` creates Python container successfully (and the files in `/clientdir` mounted sucessfully because I have the copy on host machine disk in the same directory as they located in GPDB docker container)
3. But GPDB can't connect to the Python container
4. Python container waits 20 sec and `plc_coordinator` delete it
5. The 'SELECT function();' query stays freezed until cancelled manually

Could you please give me more details how I can create connection between GPDB in docker container and Python pl/container instance?

Thanks!

**Comment by HaozhouWang** [comment]
No Python support in the master branch yet, please clone 6X_STABLE branch and re-compile it.

**Comment by yvaa** [comment]
Thanks it works in 6X_STABLE!
This issue is about GPDB in docker + pl/container and it is also works like in image!

The main condition is to mount right volumes like `/tmp` and `plcontainer_clients`. For example:
```
docker run --rm -p 5432:5432 -h dwgpdbpl --name dwgpdbpl \
    -v /docker/gpdb_data:/data \
    -v /tmp:/tmp \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /opt/greenplum-db-6.7.1/bin/plcontainer_clients:/opt/greenplum-db-6.7.1/bin/plcontainer_clients \
local/gpdb
```
