### ISSUE TITLE
Client should have a solution to use log level

### ISSUE THREAD

**Issue by paul-guo-** [greenplum-db/plcontainer#76]
Currently clients do not have a solution to filter various levels of log.

We should allow to set them. Typically solution includes: Set level in client argument or set via guc ( environment variable and/or message).

**Comment by zhangh43** [comment]
https://github.com/greenplum-db/plcontainer/commit/ca502bc71ae4fc696b2ba00cf197082dfdaa13c8

closed this Isssue
