### ISSUE TITLE
Need to check code coverage.

### ISSUE THREAD

**Issue by paul-guo-** [greenplum-db/plcontainer#78]
We really do not know much about the code coverage of our tests. We should have framework to test it.

**Comment by zhangh43** [comment]
Fixed in commits:
https://github.com/greenplum-db/plcontainer/commit/4ec6c68202aeb21d80140395c32c68433a5090d8
and 
https://github.com/greenplum-db/plcontainer/commit/4e72d2c1aed5a670c32a873f5ad8b281eab9dc56
